import { useState, useEffect, useRef } from "react";
import { useVSCode } from "../hooks/useVSCode";

interface Message {
    id: string;
    role: "user" | "assistant";
    content: string;
    timestamp: string;
}

/**
 * Lightweight markdown renderer for AI responses.
 * Handles: code blocks, inline code, bold, italic, headings, lists, links.
 */
function renderMarkdown(text: string): string {
    let html = text;

    // Escape HTML entities first (but preserve our own tags later)
    html = html
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;");

    // Code blocks: ```lang\ncode\n```
    html = html.replace(
        /```(\w*)\n([\s\S]*?)```/g,
        (_m, lang, code) =>
            `<pre class="md-codeblock"><code class="lang-${lang || "text"}">${code.trim()}</code></pre>`
    );

    // Inline code: `code`
    html = html.replace(/`([^`]+)`/g, '<code class="md-inline-code">$1</code>');

    // Headings: ### heading
    html = html.replace(/^### (.+)$/gm, '<h4 class="md-heading">$1</h4>');
    html = html.replace(/^## (.+)$/gm, '<h3 class="md-heading">$1</h3>');
    html = html.replace(/^# (.+)$/gm, '<h2 class="md-heading">$1</h2>');

    // Bold: **text**
    html = html.replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>");

    // Italic: *text*
    html = html.replace(/(?<!\*)\*(?!\*)(.+?)(?<!\*)\*(?!\*)/g, "<em>$1</em>");

    // Links: [text](url)
    html = html.replace(
        /\[([^\]]+)\]\(([^)]+)\)/g,
        '<a href="$2" class="md-link" target="_blank" rel="noopener">$1</a>'
    );

    // Unordered lists: - item
    html = html.replace(/^- (.+)$/gm, '<li class="md-li">$1</li>');
    html = html.replace(/((?:<li class="md-li">.*<\/li>\n?)+)/g, '<ul class="md-list">$1</ul>');

    // Ordered lists: 1. item
    html = html.replace(/^\d+\. (.+)$/gm, '<li class="md-li">$1</li>');

    // Line breaks (double newline = paragraph)
    html = html.replace(/\n{2,}/g, '<br/><br/>');
    html = html.replace(/\n/g, '<br/>');

    // Defense-in-depth: strip any HTML tags that weren't generated by our renderer
    const allowedTags = /^(pre|code|h[2-4]|strong|em|a|ul|li|br|span|div)\b/i;
    html = html.replace(/<\/?([a-zA-Z][a-zA-Z0-9]*)\b[^>]*>/g, (match, tag) => {
        if (allowedTags.test(tag)) return match;
        return match.replace(/</g, '&lt;').replace(/>/g, '&gt;');
    });

    return html;
}

export default function ChatTab() {
    const { postMessage } = useVSCode();
    const [messages, setMessages] = useState<Message[]>([]);
    const [input, setInput] = useState("");
    const [sending, setSending] = useState(false);
    const [streamingContent, setStreamingContent] = useState("");
    const messagesEndRef = useRef<HTMLDivElement>(null);
    const textareaRef = useRef<HTMLTextAreaElement>(null);

    // Auto-scroll to bottom
    useEffect(() => {
        messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
    }, [messages, streamingContent]);

    // Auto-resize textarea
    useEffect(() => {
        const ta = textareaRef.current;
        if (ta) {
            ta.style.height = "auto";
            ta.style.height = Math.min(ta.scrollHeight, 120) + "px";
        }
    }, [input]);

    // Listen for messages
    useEffect(() => {
        const handleMessage = (event: MessageEvent) => {
            const msg = event.data;
            switch (msg.type) {
                case "chatStreamChunk":
                    setStreamingContent(msg.payload.fullResponse);
                    break;
                case "chatResponse":
                    if (Array.isArray(msg.payload)) {
                        // Initial history load
                        setMessages(msg.payload);
                    } else if (msg.payload) {
                        // Single response
                        setMessages((prev) => [...prev, msg.payload]);
                        setStreamingContent("");
                        setSending(false);
                    }
                    break;
                case "chatCleared":
                    setMessages([]);
                    setStreamingContent("");
                    break;
                case "error":
                    setStreamingContent("");
                    setSending(false);
                    setMessages((prev) => [
                        ...prev,
                        {
                            id: `err-${Date.now()}`,
                            role: "assistant",
                            content: `⚠️ ${msg.payload}`,
                            timestamp: new Date().toISOString(),
                        },
                    ]);
                    break;
            }
        };
        window.addEventListener("message", handleMessage);
        postMessage("getChatHistory");
        return () => window.removeEventListener("message", handleMessage);
    }, [postMessage]);

    const handleSend = () => {
        if (!input.trim() || sending) return;

        const userMsg: Message = {
            id: `msg-${Date.now()}`,
            role: "user",
            content: input.trim(),
            timestamp: new Date().toISOString(),
        };

        setMessages((prev) => [...prev, userMsg]);
        setSending(true);
        setStreamingContent("");
        postMessage("sendChatMessage", { content: input.trim(), context: "chat" });
        setInput("");
    };

    const handleKeyDown = (e: React.KeyboardEvent) => {
        if (e.key === "Enter" && !e.shiftKey) {
            e.preventDefault();
            handleSend();
        }
    };

    return (
        <div className="fade-in" style={{ display: "flex", flexDirection: "column", height: "100%" }}>
            {/* Messages */}
            <div className="chat-messages" style={{ flex: 1, overflowY: "auto", paddingBottom: 8 }}>
                {messages.length === 0 && !streamingContent && (
                    <div className="empty-state">
                        <div className="empty-state-icon">💬</div>
                        <h3 className="empty-state-title">Ask Draft AI anything</h3>
                        <p className="empty-state-desc">
                            I know your codebase, project profile, scan results, and competitor research. Ask me anything specific to your project.
                        </p>
                        <div className="flex flex-col gap-sm" style={{ textAlign: "left", maxWidth: 280, margin: "0 auto" }}>
                            {[
                                "What should I build next?",
                                "Is my code secure?",
                                "How do I compare to competitors?",
                                "Review my component structure",
                            ].map((q) => (
                                <button
                                    key={q}
                                    className="btn btn-secondary btn-sm"
                                    onClick={() => {
                                        setInput(q);
                                        setTimeout(() => textareaRef.current?.focus(), 50);
                                    }}
                                    style={{ justifyContent: "flex-start", textAlign: "left" }}
                                >
                                    {q}
                                </button>
                            ))}
                        </div>
                    </div>
                )}

                {messages.map((msg) => (
                    <div key={msg.id} className={`chat-message ${msg.role}`}>
                        {msg.role === "assistant" ? (
                            <div
                                className="md-content"
                                dangerouslySetInnerHTML={{ __html: renderMarkdown(msg.content) }}
                            />
                        ) : (
                            msg.content
                        )}
                    </div>
                ))}

                {streamingContent && (
                    <div className="chat-message assistant">
                        <div
                            className="md-content"
                            dangerouslySetInnerHTML={{ __html: renderMarkdown(streamingContent) }}
                        />
                        <span className="spinner" style={{ marginLeft: 4, verticalAlign: "middle" }} />
                    </div>
                )}

                <div ref={messagesEndRef} />
            </div>

            {/* Input (this tab has its own input since it doesn't use the global ChatInput) */}
            <div style={{
                padding: "10px 0",
                borderTop: "1px solid var(--draftai-border)",
                marginTop: "auto",
            }}>
                <div className="chat-input-container">
                    <textarea
                        ref={textareaRef}
                        className="chat-input"
                        placeholder="Ask Draft AI anything..."
                        value={input}
                        onChange={(e) => setInput(e.target.value)}
                        onKeyDown={handleKeyDown}
                        rows={1}
                        disabled={sending}
                    />
                    <button
                        className="chat-send-btn"
                        onClick={handleSend}
                        disabled={!input.trim() || sending}
                    >
                        {sending ? <span className="spinner" /> : "→"}
                    </button>
                </div>
            </div>
        </div>
    );
}
